apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  url: https://github.com/bootc/netbox-chart
  ref:
    branch: master