apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  releaseName: netbox
  chart:
    spec:
      chart: netbox
      sourceRef:
        kind: GitRepository
        name: netbox
        namespace: netbox
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  # values:
  #   cache: tcp://redis-master.redis:6379
  #   ingress:
  #     enabled: false
  #     annotations:
  #       kubernetes.io/ingress.class: nginx
  #   service:
  #     type: NodePort
#       externalIPs:
#       - 192.168.100.100
